CUDA_VISIBLE_DEVICES=0 python src/train_bash.py \
    --stage sft \
    --model_name_or_path /data/share_model/Qwen-14B-Chat/ \
    --do_train \
    --template qwen \
    --dataset $1 \
    --finetuning_type full \
    --output_dir Qwen-14B-Chat-Medical \
    --per_device_train_batch_size 4 \
    --gradient_accumulation_steps 4 \
    --lr_scheduler_type cosine \
    --logging_steps 10 \
    --save_steps 1000 \
    --learning_rate 1e-5 \
    --num_train_epochs 1.0 \
    --plot_loss \
    --fp16 
